---
- name: Update apt and install dependencies 
  apt:
    update_cache: yes 
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl  
      - software-properties-common 
    state: present   
  become: yes  

- name: Installer Docker  
  apt: 
    name: docker.io 
    state: present 
  become: yes  

- name: Enable and start Docker service 
  systemd:
    name: docker 
    enabled: yes 
    state: started 
  become: yes 

- name: Add Kubernetes apt repository 
  apt_repository: 
    repo: 'deb https://apt.kubernetes.io/ kubernetes-xenial main' 
    state: present 
    filename: "kubernetes"  

- name: Install kubeadm, kubelet, kubectl 
  apt: 
    name: 
      - kubeadm 
      - kubelet 
      - kubectl
    state: present 
    update_cache: yes 
    
- name: Désactiver le swap  
  command: swapoff -a 
      



