- name: Update apt and install dependencies 
  apt:
    update_cache: yes 
    name: 
      - apt-transport-https 
      - ca-certificates 
      - curl  
      - software-properties-common 
    state: present   
  become: yes  

- name: Installer Docker  
  apt: 
    name: docker.io 
    state: present 
  become: yes  

- name: Enable and start Docker service 
  systemd:
    name: docker 
    enabled: yes 
    state: started 
  become: yes 

- name: Télécharger la clé GPG de Kubernetes
  shell: |
    mkdir -p /etc/apt/keyrings
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/k8s.gpg
  args:
    creates: /etc/apt/keyrings/k8s.gpg
  become: yes

- name: Ajouter le dépôt Kubernetes
  shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' > /etc/apt/sources.list.d/k8s.list
  args:
    creates: /etc/apt/sources.list.d/k8s.list
  become: yes
  
- name: Install kubeadm, kubelet, kubectl 
  apt: 
    name: 
      - kubeadm 
      - kubelet 
      - kubectl
    state: present 
    update_cache: yes 
    
- name: Désactiver le swap  
  command: swapoff -a 
      



